# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rAIamPPmYOup3GF8_X-0tOQjuGj6y-5
"""



from mega import Mega
import configparser
import os
import zipfile

# Load the configuration file
config = configparser.ConfigParser()
config.read("C:\Users\Sridhar\Desktop\Literature_Survey\config.ini")

if 'Mega' not in config:
    raise ValueError("Mega configuration not found in config.ini.")

# Retrieve Mega email and password from the configuration file
mega_email = config['Mega']['email']
mega_password = config['Mega']['password']

# Specify the folder you want to upload
folder_to_upload = "C:\Users\Sridhar\Desktop\ISC2.zip"

# Create a temporary zip archive of the folder
temp_zip_path = "C:\Users\Sridhar\Desktop\ISC2.zip"
with zipfile.ZipFile(temp_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(folder_to_upload):
        for file in files:
            file_path = os.path.join(root, file)
            zipf.write(file_path, os.path.relpath(file_path, folder_to_upload))

# Authenticate with your Mega account
m = Mega()
m.login(mega_email, mega_password)

# Upload the folder and its contents to Mega
m.upload(folder_to_upload)

print(f"Folder '{folder_to_upload}' uploaded to Mega ")